"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import Image from "next/image";import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {ArrowLeft,MoreHorizontal,Plus,Search,ShieldCheck,UserCheck,Users} from "lucide-react";import {AppRole,can,supabaseBrowser} from "@/lib/auth";
type Profile={id:string;full_name:string;role:AppRole;operational_scope:string;status:string;updated_at:string};
const labels:Record<AppRole,string>={super_admin:"Super Admin",fleet_manager:"Fleet Manager",dispatcher:"Dispatcher",finance_approver:"Finance Approver",viewer:"Viewer"};
export default function UsersPage(){const [items,setItems]=useState<Profile[]>([]),[role,setRole]=useState<AppRole>(),[query,setQuery]=useState(""),[invite,setInvite]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const [form,setForm]=useState({full_name:"",email:"",role:"viewer" as AppRole,operational_scope:"Semua Area"});
 async function load(){const sb=supabaseBrowser();if(!sb)return;const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data:me}=await sb.from("profiles").select("role").eq("id",user.id).single();setRole(me?.role);const {data,error}=await sb.from("profiles").select("*").order("created_at");if(error)setMessage(error.message);else setItems(data||[])}useEffect(()=>{load()},[]);
 const rows=useMemo(()=>items.filter(x=>`${x.full_name} ${x.role} ${x.operational_scope}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 async function inviteUser(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const sb=supabaseBrowser(),{data:{session}}=await sb!.auth.getSession();const res=await fetch("/api/users/invite",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${session?.access_token}`},body:JSON.stringify(form)}),json=await res.json();setBusy(false);if(!res.ok){setMessage(json.error);return}setInvite(false);setMessage("Undangan berhasil dikirim.");load()}
 async function toggle(user:Profile){const sb=supabaseBrowser();if(!sb)return;const status=user.status==="suspended"?"active":"suspended";const {error}=await sb.from("profiles").update({status,updated_at:new Date().toISOString()}).eq("id",user.id);if(error)setMessage(error.message);else{await sb.from("audit_logs").insert({actor_id:(await sb.auth.getUser()).data.user?.id,action:`user.${status}`,entity_type:"profile",entity_id:user.id});load()}}
 if(role&&!can(role,"users"))return <main className="management-page"><section className="access-denied"><ShieldCheck/><h1>Akses dibatasi</h1><p>Hanya Super Admin yang dapat mengelola pengguna.</p><Link href="/">Kembali ke Command Center</Link></section></main>;
 return <main className="management-page"><header className="management-topbar"><Link href="/" className="back-button"><ArrowLeft/></Link><Image src="/arah-logo.svg" width={44} height={44} alt="ARAH"/><div><b>ARAH</b><span>ACCESS MANAGEMENT</span></div><div className="management-profile">AW</div></header><section className="management-content"><div className="management-heading"><div><p>ADMINISTRATION / USER ACCESS</p><h1>Pengguna & Akses</h1><span>Kelola akun, peran, dan cakupan akses operasional.</span></div><button disabled={!can(role,"users")} onClick={()=>setInvite(true)}><Plus/> Tambah Pengguna</button></div>{message&&<div className="management-message">{message}</div>}<div className="access-stats"><article><Users/><div><span>Total pengguna</span><b>{items.length}</b></div></article><article><UserCheck/><div><span>Akun aktif</span><b>{items.filter(x=>x.status==="active").length}</b></div></article><article><ShieldCheck/><div><span>Administrator</span><b>{items.filter(x=>x.role==="super_admin").length}</b></div></article></div><section className="users-panel"><div className="users-toolbar"><label><Search/><input placeholder="Cari nama, cakupan, atau peran…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="table-wrap"><table className="users-table"><thead><tr><th>Pengguna</th><th>Peran</th><th>Cakupan</th><th>Status</th><th>Diperbarui</th><th/></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td><div className="user-cell"><i>{u.full_name.split(" ").map(x=>x[0]).slice(0,2).join("")}</i><span><b>{u.full_name}</b><small>{u.id.slice(0,8)}</small></span></div></td><td>{labels[u.role]}</td><td>{u.operational_scope}</td><td><span className={`user-status ${u.status}`}>{u.status}</span></td><td>{new Date(u.updated_at).toLocaleDateString("id-ID")}</td><td><button className="row-more" title={u.status==="suspended"?"Aktifkan":"Suspend"} onClick={()=>toggle(u)}><MoreHorizontal/></button></td></tr>)}</tbody></table></div></section></section>{invite&&<div className="modal-backdrop" onClick={()=>setInvite(false)}><form className="invite-modal" onSubmit={inviteUser} onClick={e=>e.stopPropagation()}><p>AKSES BARU</p><h2>Undang pengguna</h2><label>Nama lengkap<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Peran<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as AppRole})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Cakupan<input required value={form.operational_scope} onChange={e=>setForm({...form,operational_scope:e.target.value})}/></label><div><button type="button" className="cancel" onClick={()=>setInvite(false)}>Batal</button><button className="send" disabled={busy}>{busy?"Mengirim…":"Kirim Undangan"}</button></div></form></div>}</main>}
