"use client";
/* eslint-disable react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */
import dynamic from "next/dynamic";
import Image from "next/image";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {AnimatePresence,motion} from "framer-motion";
import {AlertTriangle,Bell,Check,ChevronLeft,ChevronRight,CircleDollarSign,Eye,FileDown,History,Layers3,LayoutDashboard,LogOut,Map,Menu,Navigation,PackageCheck,PanelLeftClose,Pin,Plus,Route,Search,Settings,Truck,Users,UserRound,WalletCards,Warehouse,Wrench,X,Maximize2,Minimize2} from "lucide-react";
import {AppRole,can,supabaseBrowser} from "@/lib/auth";
import {copy,useDisplayPreferences} from "@/lib/display-preferences";
import FleetControlPanel from "@/components/FleetControlPanel";
import "./fleet-focus.css";
import "./command-center.css";
const FleetMap=dynamic(()=>import("@/components/FleetMap"),{ssr:false});

type Vehicle={id:string;plate_number:string;vehicle_type:string;status:string;driver_name:string|null;driver_id:string|null;fuel_percent:number|null;last_lat:number|null;last_lng:number|null;last_gps_at:string|null;odometer_km:number|null;capacity_kg:number|null;brand:string|null;model:string|null;year:number|null;vendor_name:string|null;photo_url:string|null;device_status:string|null};
type Order={id:string;order_number:string;customer_name:string|null;origin:string;destination:string;status:string;vehicle_id:string|null;driver_id:string|null;cargo_description:string|null;cargo_weight_kg:number|null;scheduled_at:string|null;eta:string|null;pod_url:string|null;notes:string|null;cargo_category:string|null;cargo_quantity:number|null;cargo_unit:string|null;cargo_volume_m3:number|null;declared_value:number|null;handling_instructions:string[]|null;pickup_pic:string|null;recipient_pic:string|null;document_url:string|null};
type LiveRoute={id:string;vehicle_id:string|null;status:string|null;eta:string|null;geometry:{coordinates?:[number,number][]}|null};
type RouteQueryRow={id:string;geometry:LiveRoute["geometry"];orders:{vehicle_id:string|null;status:string|null;eta:string|null}|{vehicle_id:string|null;status:string|null;eta:string|null}[]|null};
type Fund={id:string;category:string;amount:number;description:string|null;status:string;vehicle_id:string|null;order_id:string|null;settlement_amount:number|null;settled_at:string|null};
type Issue={id:string;title:string;description:string|null;severity:string;status:string;resolved_at:string|null;vehicle_id:string|null;assigned_to:string|null;due_at:string|null;resolution:string|null;created_at?:string};
type Driver={id:string;full_name:string;phone:string|null;license_number:string|null;license_expiry:string|null;status:string;photo_url?:string|null};
type Master={id:string;name:string;status?:string;address?:string};
type Notice={id:string;title:string;body:string|null;read_at:string|null};
type Profile={id:string;full_name:string;role:AppRole;status:string};
type Modal="vehicle"|"order"|"fund"|"issue"|"driver"|"vendor"|"branch"|"settings"|"notifications"|"order-detail"|"fund-detail"|"issue-detail"|null;

const navGroups=[
 {title:"Monitoring",items:[[LayoutDashboard,"Command Center","Pusat Kendali"],[Map,"Live Map","Peta Langsung"]]},
 {title:"Operasional",items:[[Truck,"Armada","Armada"],[UserRound,"Pengemudi","Pengemudi"],[PackageCheck,"Order Handling","Penanganan Order"],[WalletCards,"Dana Operasional","Dana Operasional"],[Wrench,"Issue Lapangan","Issue Lapangan"]]},
 {title:"Data & Laporan",items:[[Warehouse,"Master Data","Data Master"],[History,"Riwayat Armada","Riwayat Armada"]]}
] as const;

export default function Home(){
 const {prefs,setPrefs}=useDisplayPreferences(),text=copy[prefs.language];
 const [active,setActive]=useState("Command Center"),[sidebar,setSidebar]=useState(true),[panel,setPanel]=useState(true),[expanded,setExpanded]=useState(false),[search,setSearch]=useState(""),[mapReset,setMapReset]=useState(0),[modal,setModal]=useState<Modal>(null),[selected,setSelected]=useState<string>(""),[selectedVehicle,setSelectedVehicle]=useState<string>(""),[focusedVehicles,setFocusedVehicles]=useState<string[]>([]),[role,setRole]=useState<AppRole>(),[uid,setUid]=useState(""),[vehicles,setVehicles]=useState<Vehicle[]>([]),[orders,setOrders]=useState<Order[]>([]),[liveRoutes,setLiveRoutes]=useState<LiveRoute[]>([]),[funds,setFunds]=useState<Fund[]>([]),[issues,setIssues]=useState<Issue[]>([]),[drivers,setDrivers]=useState<Driver[]>([]),[vendors,setVendors]=useState<Master[]>([]),[branches,setBranches]=useState<Master[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[notices,setNotices]=useState<Notice[]>([]),[toast,setToast]=useState("");
 const sb=supabaseBrowser();
 const flash=(x:string)=>{setToast(x);window.setTimeout(()=>setToast(""),2600)};
 async function load(){if(!sb)return;const {data:{user}}=await sb.auth.getUser();if(!user)return;setUid(user.id);const [p,v,o,r,f,i,d,ve,b,pr,n]=await Promise.all([sb.from("profiles").select("role,status").eq("id",user.id).single(),sb.from("vehicles").select("*").order("created_at",{ascending:false}),sb.from("orders").select("*").order("created_at",{ascending:false}),sb.from("routes").select("id,order_id,geometry,orders!inner(vehicle_id,status,eta)").in("orders.status",["assigned","pickup","in_transit"]),sb.from("operational_funds").select("*").order("created_at",{ascending:false}),sb.from("field_issues").select("*").order("created_at",{ascending:false}),sb.from("drivers").select("*").order("created_at",{ascending:false}),sb.from("vendors").select("*").order("created_at",{ascending:false}),sb.from("branches").select("*").order("created_at",{ascending:false}),sb.from("profiles").select("id,full_name,role,status").eq("status","active"),sb.from("notifications").select("*").order("created_at",{ascending:false}).limit(20)]);if(p.data?.status==="suspended"){await sb.auth.signOut();return}const routeRows=(r.data||[]) as unknown as RouteQueryRow[];setRole(p.data?.role);setVehicles(v.data||[]);setOrders(o.data||[]);setLiveRoutes(routeRows.map(x=>({id:x.id,vehicle_id:Array.isArray(x.orders)?x.orders[0]?.vehicle_id||null:x.orders?.vehicle_id||null,status:(Array.isArray(x.orders)?x.orders[0]?.status:x.orders?.status)||null,eta:(Array.isArray(x.orders)?x.orders[0]?.eta:x.orders?.eta)||null,geometry:x.geometry})));setFunds(f.data||[]);setIssues(i.data||[]);setDrivers(d.data||[]);setVendors(ve.data||[]);setBranches(b.data||[]);setProfiles((pr.data||[]) as Profile[]);setNotices(n.data||[])}
 useEffect(()=>{load();if(!sb)return;const channel=sb.channel("arah-operations").on("postgres_changes",{event:"*",schema:"public"},load).subscribe();return()=>{sb.removeChannel(channel)}},[]);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem("arah-focused-vehicles")||"[]");if(Array.isArray(saved))setFocusedVehicles(saved)}catch{}},[]);
 useEffect(()=>{sessionStorage.setItem("arah-focused-vehicles",JSON.stringify(focusedVehicles))},[focusedVehicles]);
 const filtered=useMemo(()=>vehicles.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())),[vehicles,search]);
 useEffect(()=>{if(!selectedVehicle&&vehicles.length)setSelectedVehicle(vehicles.find(v=>v.status==="in_transit")?.id||vehicles[0].id)},[vehicles,selectedVehicle]);
 const choose=(x:string)=>{setActive(x);setPanel(true)};const pending=funds.filter(x=>x.status==="pending"),openIssues=issues.filter(x=>!['resolved','closed'].includes(x.status));const available=vehicles.length?Math.round(vehicles.filter(x=>x.status==="available").length/vehicles.length*100):0;
 async function audit(action:string,type:string,id?:string,metadata={}){await sb?.from("audit_logs").insert({actor_id:uid,action,entity_type:type,entity_id:id,metadata})}
 async function remove(table:string,id:string){if(!confirm("Hapus data ini?"))return;const {error}=await sb!.from(table).delete().eq("id",id);if(error)flash(error.message);else{await audit(`${table}.deleted`,table,id);flash("Data berhasil dihapus");load()}}
 function openDetail(kind:Modal,id:string){setSelected(id);setModal(kind)}
 function toggleVehicleFocus(id:string){setFocusedVehicles(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);setPanel(true)}
 function inspectVehicle(id:string){setSelectedVehicle(id);setActive("Command Center");setPanel(true)}
 async function fundDecision(x:Fund,status:"approved"|"rejected"){if(!can(role,"finance")){flash("Role Anda tidak memiliki akses approval");return}const reason=status==="rejected"?window.prompt("Tuliskan alasan penolakan:")||"":null;if(status==="rejected"&&!reason){flash("Alasan penolakan wajib diisi");return}const {error}=await sb!.rpc("review_fund",{p_fund:x.id,p_decision:status,p_reason:reason});if(error)flash(error.message);else{flash(status==="approved"?"Dana disetujui":"Dana ditolak");load()}}
 function exportCsv(){const rows=orders.map(o=>[o.order_number,o.customer_name||"",o.origin,o.destination,o.status]);const csv=[["Order","Customer","Origin","Destination","Status"],...rows].map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`arah-orders-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}

 return <main className={`map-app ${sidebar?"":"sidebar-collapsed"}`}>
  <div className="map-stage"><FleetMap focusedIds={focusedVehicles} onSelect={inspectVehicle} vehicles={vehicles} liveRoutes={liveRoutes} traffic={prefs.traffic} motion={prefs.motion} resetToken={mapReset}/></div>
  <header className="map-header"><button className="square-action mobile-only" onClick={()=>setSidebar(!sidebar)}><Menu/></button><div className="map-brand"><Image src="/arah-logo.png" width={44} height={44} alt="ARAH"/><div><b>ARAH</b><span>FLEET COMMAND CENTER</span></div></div><div className="live-status"><i/> LIVE OPERATIONS <span>SUPABASE REALTIME</span></div><div className="header-actions"><label className="map-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari armada…"/></label><button className="square-action has-dot" onClick={()=>setModal("notifications")} aria-label="Notifikasi"><Bell/></button><Link className="avatar" href="/users">AW</Link></div></header>
  <aside className="map-sidebar"><button className="sidebar-toggle" onClick={()=>setSidebar(!sidebar)}>{sidebar?<PanelLeftClose/>:<ChevronRight/>}</button><div className="nav-caption">{text.workspace.toUpperCase()}</div>{navGroups.map(group=><div className="nav-group" key={group.title}><div className="nav-caption">{group.title}</div>{group.items.map(([Icon,l,label])=><button key={l} className={active===l?"map-nav active":"map-nav"} onClick={()=>choose(l)}><Icon/><span>{label}</span></button>)}</div>)}<div className="nav-spacer"/><button className={`map-nav ${prefs.traffic?"active":""}`} onClick={()=>setPrefs({...prefs,traffic:!prefs.traffic})}><Route/><span>{text.traffic}</span></button>{can(role,"users")&&<Link className="map-nav" href="/users"><Users/><span>{text.users}</span></Link>}{can(role,"settings")&&<><Link className="map-nav" href="/settings"><Settings/><span>{text.settings}</span></Link><Link className="map-nav sub-nav" href="/settings?tab=connectors"><Route/><span>Konektor & GPS</span></Link><Link className="map-nav sub-nav" href="/settings?tab=display"><Eye/><span>Tampilan</span></Link></>}<button className="map-nav" onClick={async()=>{await audit("auth.logout","session");await sb?.auth.signOut()}}><LogOut/><span>{text.logout}</span></button></aside>
  <section className="kpi-dock"><Kpi icon={Truck} label="Availability" value={`${available}%`} tone="green" onClick={()=>choose("Armada")}/><Kpi icon={CircleDollarSign} label="Dana Pending" value={`Rp ${pending.reduce((a,b)=>a+Number(b.amount),0).toLocaleString("id-ID")}`} tone="blue" onClick={()=>choose("Dana Operasional")}/><Kpi icon={PackageCheck} label="Order Aktif" value={`${orders.filter(x=>!["delivered","cancelled"].includes(x.status)).length}`} tone="cyan" onClick={()=>choose("Order Handling")}/><Kpi icon={AlertTriangle} label="Issue Lapangan" value={`${openIssues.length}`} tone="orange" onClick={()=>choose("Issue Lapangan")}/></section>
  <AnimatePresence>{panel&&<motion.section initial={{opacity:0,x:25}} animate={{opacity:1,x:0}} className={`floating-window ${expanded?"expanded":""}`}><div className="window-bar"><div><span>OPERATIONS / LIVE</span><h1>{active}</h1></div><div><button onClick={exportCsv} title="Ekspor CSV"><FileDown/></button><button onClick={()=>setExpanded(!expanded)}>{expanded?<Minimize2/>:<Maximize2/>}</button><button onClick={()=>setPanel(false)}><X/></button></div></div><div className="window-content">
   {(active==="Command Center"||active==="Live Map")&&<><div className="fleet-focus-head"><Title title="Armada & Fokus Peta" sub="Pilih armada untuk detail; gunakan pin untuk fokus peta"/>{focusedVehicles.length>0&&<button onClick={()=>setFocusedVehicles([])}><Eye/> Lihat Semua</button>}</div><div className="focus-fleet-list">{filtered.map(v=><div key={v.id} className={`${focusedVehicles.includes(v.id)?"pinned ":""}${selectedVehicle===v.id?"selected":""}`}><button className="vehicle-select" onClick={()=>inspectVehicle(v.id)}><span><b>{v.plate_number}</b><small>{v.driver_name||drivers.find(d=>d.id===v.driver_id)?.full_name||"Tanpa pengemudi"}</small></span><em>{v.status}</em></button><button className="pin-action" onClick={()=>toggleVehicleFocus(v.id)} title={focusedVehicles.includes(v.id)?"Lepas pin":"Pin ke peta"}><Pin/></button></div>)}</div><FleetControlPanel vehicle={vehicles.find(v=>v.id===selectedVehicle)||null} orders={orders} drivers={drivers} issues={issues} funds={funds} role={role} onOrder={id=>openDetail("order-detail",id)} onAction={flash}/></>}
   {active==="Armada"&&<EntitySection title="Master Armada" add={()=>setModal("vehicle")} allowed={can(role,"operate")}><Rows items={filtered.map(x=>({id:x.id,title:x.plate_number,sub:`${x.vehicle_type} · ${x.driver_name||drivers.find(d=>d.id===x.driver_id)?.full_name||"Tanpa pengemudi"}`,tag:x.status}))} onDelete={id=>remove("vehicles",id)}/></EntitySection>}
   {active==="Pengemudi"&&<EntitySection title="Master Pengemudi" add={()=>setModal("driver")} allowed={can(role,"operate")}><Rows items={drivers.map(x=>({id:x.id,title:x.full_name,sub:`${x.phone||"Tanpa telepon"} · SIM ${x.license_number||"-"}`,tag:x.status}))} onDelete={id=>remove("drivers",id)}/></EntitySection>}
   {active==="Order Handling"&&<EntitySection title="Order Handling" add={()=>setModal("order")} allowed={can(role,"operate")}><Rows items={orders.map(x=>({id:x.id,title:x.order_number,sub:`${x.customer_name||"Customer"} · ${x.origin} → ${x.destination}`,tag:x.status}))} onClick={id=>openDetail("order-detail",id)} onDelete={id=>remove("orders",id)}/></EntitySection>}
   {active==="Dana Operasional"&&<EntitySection title="Dana & Settlement" add={()=>setModal("fund")} allowed={can(role,"operate")}><div className="approval-list">{funds.map(x=><div className="approval-mini" key={x.id} onClick={()=>openDetail("fund-detail",x.id)}><div><b>{x.category}</b><small>{x.status}</small><strong>Rp {Number(x.amount).toLocaleString("id-ID")}</strong></div>{x.status==="pending"&&can(role,"finance")&&<><button className="reject" aria-label="Tolak" onClick={e=>{e.stopPropagation();fundDecision(x,"rejected")}}><X/></button><button className="approve" aria-label="Setujui" onClick={e=>{e.stopPropagation();fundDecision(x,"approved")}}><Check/></button></>}</div>)}</div></EntitySection>}
   {active==="Issue Lapangan"&&<EntitySection title="Issue & SLA" add={()=>setModal("issue")} allowed={can(role,"operate")}><Rows items={issues.map(x=>({id:x.id,title:x.title,sub:`${x.description||"Tanpa deskripsi"}${x.due_at?` · SLA ${new Date(x.due_at).toLocaleString("id-ID")}`:""}`,tag:x.status||x.severity}))} onClick={id=>openDetail("issue-detail",id)} onDelete={id=>remove("field_issues",id)}/></EntitySection>}
   {active==="Riwayat Armada"&&<EntitySection title="Riwayat Armada & Incident" add={()=>setModal("issue")} allowed={can(role,"operate")}><Rows items={issues.map(x=>({id:x.id,title:x.title,sub:`${vehicles.find(v=>v.id===x.vehicle_id)?.plate_number||"Tanpa armada"} · ${x.description||"Tanpa deskripsi"}`,tag:x.status}))} onClick={id=>openDetail("issue-detail",id)}/></EntitySection>}
   {active==="Master Data"&&<><EntitySection title="Vendor" add={()=>setModal("vendor")} allowed={can(role,"operate")}><Rows items={vendors.map(x=>({id:x.id,title:x.name,sub:"Mitra operasional",tag:x.status||"active"}))} onDelete={id=>remove("vendors",id)}/></EntitySection><EntitySection title="Cabang & Depot" add={()=>setModal("branch")} allowed={can(role,"operate")}><Rows items={branches.map(x=>({id:x.id,title:x.name,sub:x.address||"Alamat belum diisi",tag:"branch"}))} onDelete={id=>remove("branches",id)}/></EntitySection></>}
  </div></motion.section>}</AnimatePresence>
  {!panel&&<button className="reopen-panel" onClick={()=>setPanel(true)}><ChevronLeft/> Buka panel</button>}<div className="map-tools"><button aria-label="Tampilkan atau sembunyikan trafik" className={prefs.traffic?"active":""} onClick={()=>setPrefs({...prefs,traffic:!prefs.traffic})}><Layers3/></button><button aria-label="Pusatkan map" onClick={()=>{setFocusedVehicles([]);setMapReset(x=>x+1)}}><Navigation/></button></div><div className="provider-pill"><Route/> OSRM ROAD-SNAPPED <i/> GPS API READY</div>
  {modal&&<OperationsModal type={modal} selected={selected} role={role} uid={uid} vehicles={vehicles} drivers={drivers} profiles={profiles} orders={orders} funds={funds} issues={issues} notices={notices} close={()=>setModal(null)} done={m=>{setModal(null);flash(m||"Data berhasil disimpan");load()}}/>}{toast&&<div className="action-toast"><Check/>{toast}</div>}
 </main>
}

function Kpi({icon:Icon,label,value,tone,onClick}:{icon:typeof Truck;label:string;value:string;tone:string;onClick:()=>void}){return <button className={`mini-kpi ${tone}`} onClick={onClick}><Icon/><span><small>{label}</small><b>{value}</b></span><ChevronRight/></button>}
function Title({title,sub}:{title:string;sub:string}){return <div className="section-title"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function EntitySection({title,add,allowed,children}:{title:string;add:()=>void;allowed:boolean;children:React.ReactNode}){return <><div className="entity-head"><Title title={title} sub="Tersimpan dan tersinkron realtime"/><button disabled={!allowed} onClick={add}><Plus/> Tambah</button></div>{children}</>}
function Rows({items,onClick,onDelete}:{items:{id:string;title:string;sub:string;tag:string}[];onClick?:(id:string)=>void;onDelete?:(id:string)=>void}){if(!items.length)return <div className="window-empty">Belum ada data.</div>;return <div className="stat-rows">{items.map(x=><button key={x.id} onClick={()=>onClick?.(x.id)}><div><b>{x.title}</b><small>{x.sub}</small></div><span>{x.tag}</span>{onDelete?<X onClick={e=>{e.stopPropagation();onDelete(x.id)}}/>:<ChevronRight/>}</button>)}</div>}

function OperationsModal({type,selected,role,uid,vehicles,drivers,profiles,orders,funds,issues,notices,close,done}:{type:Exclude<Modal,null>;selected:string;role?:AppRole;uid:string;vehicles:Vehicle[];drivers:Driver[];profiles:Profile[];orders:Order[];funds:Fund[];issues:Issue[];notices:Notice[];close:()=>void;done:(m?:string)=>void}){
 const sb=supabaseBrowser(),[busy,setBusy]=useState(false),[error,setError]=useState(""),[form,setForm]=useState<Record<string,string>>({status:"available",severity:"medium",amount:"",plate_number:"",vehicle_type:"",driver_name:"",driver_id:"",order_number:"",customer_name:"",origin:"",destination:"",vehicle_id:"",cargo_description:"",cargo_weight_kg:"",scheduled_at:"",eta:"",category:"",description:"",title:"",phone:"",license_number:"",license_expiry:"",full_name:"",name:"",address:"",settlement_amount:"",settlement_note:"",resolution:"",due_at:""});
 const order=orders.find(x=>x.id===selected),fund=funds.find(x=>x.id===selected),issue=issues.find(x=>x.id===selected);
 const field=(name:string,label:string,input="text")=><label>{label}<input type={input} value={form[name]||""} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>;
 const select=(name:string,label:string,options:{v:string;l:string}[])=> <label>{label}<select value={form[name]||""} onChange={e=>setForm({...form,[name]:e.target.value})}>{options.map(x=><option key={x.v} value={x.v}>{x.l}</option>)}</select></label>;
 async function log(action:string,entity:string,id?:string){await sb?.from("audit_logs").insert({actor_id:uid,action,entity_type:entity,entity_id:id})}
 async function save(e:React.FormEvent){e.preventDefault();if(!sb)return;setBusy(true);setError("");let table="",payload:Record<string,unknown>={};
  if(type==="vehicle"){table="vehicles";payload={plate_number:form.plate_number,vehicle_type:form.vehicle_type,driver_name:form.driver_name||null,driver_id:form.driver_id||null,status:form.status,capacity_kg:Number(form.capacity_kg)||null}}
  if(type==="driver"){table="drivers";payload={full_name:form.full_name,phone:form.phone||null,license_number:form.license_number||null,license_expiry:form.license_expiry||null,status:"available"}}
  if(type==="vendor"){table="vendors";payload={name:form.name,status:"active"}}
  if(type==="branch"){table="branches";payload={name:form.name,address:form.address||null}}
  if(type==="order"){table="orders";payload={order_number:form.order_number,customer_name:form.customer_name||null,origin:form.origin,destination:form.destination,vehicle_id:form.vehicle_id||null,driver_id:form.driver_id||null,cargo_description:form.cargo_description||null,cargo_weight_kg:Number(form.cargo_weight_kg)||null,scheduled_at:form.scheduled_at||null,eta:form.eta||null,status:form.vehicle_id?"assigned":"planned"}}
  if(type==="fund"){table="operational_funds";payload={category:form.category,description:form.description||null,amount:Number(form.amount),vehicle_id:form.vehicle_id||null,order_id:form.order_id||null,status:"pending",requested_by:uid}}
  if(type==="issue"){table="field_issues";payload={title:form.title,description:form.description,severity:form.severity,vehicle_id:form.vehicle_id||null,order_id:form.order_id||null,due_at:form.due_at||null,status:"reported",reported_by:uid}}
  const {data,error}=await sb.from(table).insert(payload).select("id").single();setBusy(false);if(error){setError(error.message);return}await log(`${table}.created`,table,data?.id);done()}
 async function upload(file:File,entityType:string,entityId:string){if(!sb)throw new Error("Supabase tidak tersedia");if(file.size>10485760)throw new Error("Ukuran file maksimal 10 MB");const path=`${uid}/${entityType}/${entityId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const result=await sb.storage.from("operations").upload(path,file,{contentType:file.type});if(result.error)throw result.error;const meta=await sb.from("operation_attachments").insert({entity_type:entityType,entity_id:entityId,storage_path:path,file_name:file.name,mime_type:file.type,size_bytes:file.size,uploaded_by:uid});if(meta.error){await sb.storage.from("operations").remove([path]);throw meta.error}return path}
 async function orderStatus(status:string){if(!order||!can(role,"operate"))return;setBusy(true);setError("");try{let podPath:string|null=null;if(status==="delivered"){const file=(document.getElementById("pod-file") as HTMLInputElement|null)?.files?.[0];if(!order.pod_url&&!file)throw new Error("POD wajib diunggah sebelum delivery");if(file)podPath=await upload(file,"order_pod",order.id)}const {error}=await sb!.rpc("transition_order",{p_order:order.id,p_status:status,p_note:form.notes||null,p_pod_path:podPath});if(error)throw error;done(`Status order menjadi ${status}`)}catch(err){setError(err instanceof Error?err.message:"Workflow order gagal")}finally{setBusy(false)}}
 async function settle(){if(!fund||!can(role,"finance"))return;const {error}=await sb!.from("operational_funds").update({settlement_amount:Number(form.settlement_amount),settlement_note:form.settlement_note,settled_at:new Date().toISOString()}).eq("id",fund.id);if(error)setError(error.message);else{await log("fund.settled","operational_fund",fund.id);done("Settlement tersimpan")}}
 async function issueStatus(status:string){if(!issue||!can(role,"operate"))return;setBusy(true);const {error}=await sb!.rpc("update_issue_status",{p_issue:issue.id,p_status:status,p_assignee:form.assigned_to||null,p_resolution:form.resolution||null});setBusy(false);if(error)setError(error.message);else done(`Issue menjadi ${status}`)}
 async function markRead(id:string){const {error}=await sb!.rpc("mark_notification_read",{p_id:id});if(error)setError(error.message);else done("Notifikasi ditandai dibaca")}
 async function saveSettings(e:React.FormEvent){e.preventDefault();if(!can(role,"users"))return;const value={timezone:form.timezone||"Asia/Jakarta",gps_stale_minutes:Number(form.gps_stale_minutes||10),sla_warning_minutes:Number(form.sla_warning_minutes||30)};const {error}=await sb!.from("app_settings").update({value,updated_by:uid,updated_at:new Date().toISOString()}).eq("key","operations");if(error)setError(error.message);else done("Pengaturan diperbarui")}
 if(type==="notifications")return <Shell title="Notification Center" close={close}>{notices.length?notices.map(n=><article key={n.id} className={n.read_at?"read":"unread"}><b>{n.title}</b><small>{n.body}</small>{!n.read_at&&<button onClick={()=>markRead(n.id)}>Tandai dibaca</button>}</article>):<p>Belum ada notifikasi.</p>}</Shell>;
 if(type==="settings")return <Shell title="Pengaturan Operasional" close={close}><form onSubmit={saveSettings}>{field("timezone","Timezone")}{field("gps_stale_minutes","GPS stale (menit)","number")}{field("sla_warning_minutes","Peringatan SLA (menit)","number")}<button disabled={!can(role,"users")}>Simpan Pengaturan</button></form>{error&&<div className="auth-error">{error}</div>}<small>{can(role,"users")?"Konfigurasi Super Admin aktif.":"Hanya Super Admin yang dapat mengubah konfigurasi."}</small></Shell>;
 if(type==="order-detail"&&order){const next:Record<string,[string,string][]>= {planned:[["assigned","Assign"],["cancelled","Batal"]],assigned:[["pickup","Pickup"],["cancelled","Batal"]],pickup:[["in_transit","Transit"],["cancelled","Batal"]],in_transit:[["delivered","Delivered"]]};const assignedVehicle=vehicles.find(v=>v.id===order.vehicle_id),assignedDriver=drivers.find(d=>d.id===order.driver_id),tripFunds=funds.filter(f=>f.order_id===order.id),tripIssues=issues.filter(i=>i.vehicle_id===order.vehicle_id&&!['resolved','closed'].includes(i.status));return <Shell title={`Order ${order.order_number}`} close={close}><div className="order-detail-grid"><section><small>PELANGGAN & STATUS</small><b>{order.customer_name||"Customer"}</b><span className="detail-status">{order.status}</span></section><section><small>ARMADA & DRIVER</small><b>{assignedVehicle?.plate_number||"Belum ditugaskan"}</b><span>{assignedDriver?.full_name||"Driver belum ditugaskan"}</span></section></div><div className="cargo-detail"><small>DETAIL MUATAN</small><h3>{order.cargo_description||"Muatan belum diisi"}</h3><div><span>{order.cargo_category||"General Cargo"}</span><span>{order.cargo_quantity||1} {order.cargo_unit||"shipment"}</span><span>{Number(order.cargo_weight_kg||0).toLocaleString("id-ID")} kg</span><span>{order.cargo_volume_m3||0} m³</span></div>{order.handling_instructions?.length?<p>Instruksi: {order.handling_instructions.join(" · ")}</p>:null}<p>Nilai deklarasi: <b>Rp {Number(order.declared_value||0).toLocaleString("id-ID")}</b></p></div><div className="order-route-detail"><div><small>PICKUP</small><b>{order.origin}</b><span>PIC: {order.pickup_pic||"-"}</span></div><ChevronRight/><div><small>DELIVERY</small><b>{order.destination}</b><span>Penerima: {order.recipient_pic||"-"}</span></div></div><div className="order-support"><span>Dana perjalanan <b>Rp {tripFunds.reduce((a,b)=>a+Number(b.amount),0).toLocaleString("id-ID")}</b></span><span>Incident aktif <b>{tripIssues.length}</b></span><span>ETA <b>{order.eta?new Date(order.eta).toLocaleString("id-ID"):"-"}</b></span></div>{order.document_url&&<a className="document-link" href={order.document_url} target="_blank">Lihat surat jalan / dokumen</a>}{field("notes","Catatan event")}{order.status==="in_transit"&&<label>Proof of Delivery<input id="pod-file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label>}<div className="status-actions">{(next[order.status]||[]).map(([v,l])=><button disabled={busy||!can(role,"operate")} key={v} onClick={()=>orderStatus(v)}>{l}</button>)}</div>{error&&<div className="auth-error">{error}</div>}</Shell>}
 if(type==="fund-detail"&&fund)return <Shell title={`Dana: ${fund.category}`} close={close}><div className="workflow-summary"><b>Rp {Number(fund.amount).toLocaleString("id-ID")}</b><span>Status: {fund.status}</span><small>{fund.description||"Tanpa deskripsi"}</small></div>{fund.status==="approved"&&!fund.settled_at&&<>{field("settlement_amount","Nilai realisasi","number")}{field("settlement_note","Catatan settlement")}<button onClick={settle}>Simpan Settlement</button></>}{fund.settled_at&&<p>Settlement Rp {Number(fund.settlement_amount).toLocaleString("id-ID")}</p>}{error&&<div className="auth-error">{error}</div>}</Shell>;
 if(type==="issue-detail"&&issue){const next:Record<string,[string,string][]>= {reported:[["assigned","Assign"]],assigned:[["in_progress","Proses"],["resolved","Resolve"]],in_progress:[["resolved","Resolve"]],resolved:[["closed","Tutup"]]};return <Shell title={`Issue: ${issue.title}`} close={close}><div className="workflow-summary"><b>{issue.severity.toUpperCase()} · {issue.status}</b><span>{issue.description}</span><small>{issue.due_at?`SLA: ${new Date(issue.due_at).toLocaleString("id-ID")}`:"SLA belum ditetapkan"}</small></div>{issue.status==="reported"&&select("assigned_to","PIC",[{v:"",l:"Pilih PIC"},...profiles.filter(x=>["super_admin","fleet_manager","dispatcher"].includes(x.role)).map(x=>({v:x.id,l:x.full_name}))])}{["assigned","in_progress"].includes(issue.status)&&field("resolution","Resolusi / tindakan")}<div className="status-actions">{(next[issue.status]||[]).map(([v,l])=><button key={v} disabled={busy||!can(role,"operate")} onClick={()=>issueStatus(v)}>{l}</button>)}</div>{error&&<div className="auth-error">{error}</div>}</Shell>}
 return <div className="modal-backdrop" onClick={close}><form className="ops-modal" onSubmit={save} onClick={e=>e.stopPropagation()}><h2>Tambah {type}</h2>
  {type==="vehicle"&&<>{field("plate_number","Nomor polisi")}{field("vehicle_type","Tipe kendaraan")}{field("capacity_kg","Kapasitas (kg)","number")}{field("driver_name","Nama pengemudi (opsional)")}{select("driver_id","Master pengemudi",[{v:"",l:"Tanpa pengemudi"},...drivers.map(x=>({v:x.id,l:x.full_name}))])}{select("status","Status",["available","in_transit","maintenance","offline"].map(x=>({v:x,l:x})))}</>}
  {type==="driver"&&<>{field("full_name","Nama lengkap")}{field("phone","Telepon")}{field("license_number","Nomor SIM")}{field("license_expiry","Masa berlaku SIM","date")}</>}
  {type==="vendor"&&field("name","Nama vendor")}{type==="branch"&&<>{field("name","Nama cabang/depot")}{field("address","Alamat")}</>}
  {type==="order"&&<>{field("order_number","Nomor order")}{field("customer_name","Customer")}{field("origin","Asal")}{field("destination","Tujuan")}{field("cargo_description","Deskripsi muatan")}{field("cargo_weight_kg","Berat (kg)","number")}{field("scheduled_at","Jadwal pickup","datetime-local")}{field("eta","ETA","datetime-local")}{select("vehicle_id","Armada",[{v:"",l:"Belum ditugaskan"},...vehicles.map(x=>({v:x.id,l:x.plate_number}))])}{select("driver_id","Pengemudi",[{v:"",l:"Belum ditugaskan"},...drivers.map(x=>({v:x.id,l:x.full_name}))])}</>}
  {type==="fund"&&<>{field("category","Kategori")}{field("description","Keperluan")}{field("amount","Nominal","number")}{select("order_id","Order",[{v:"",l:"Tanpa order"},...orders.map(x=>({v:x.id,l:x.order_number}))])}{select("vehicle_id","Armada",[{v:"",l:"Tanpa armada"},...vehicles.map(x=>({v:x.id,l:x.plate_number}))])}</>}
  {type==="issue"&&<>{field("title","Judul")}{field("description","Deskripsi")}{select("severity","Severity",["low","medium","high","critical"].map(x=>({v:x,l:x})))}{field("due_at","Batas SLA","datetime-local")}{select("order_id","Order",[{v:"",l:"Tanpa order"},...orders.map(x=>({v:x.id,l:x.order_number}))])}{select("vehicle_id","Armada",[{v:"",l:"Tanpa armada"},...vehicles.map(x=>({v:x.id,l:x.plate_number}))])}</>}
  {error&&<div className="auth-error">{error}</div>}<div><button type="button" onClick={close}>Batal</button><button disabled={busy}>{busy?"Menyimpan…":"Simpan"}</button></div></form></div>
}
function Shell({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onClick={close}><section className="ops-modal" onClick={e=>e.stopPropagation()}><div className="modal-title"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</section></div>}
