"use client";
/* eslint-disable react-hooks/exhaustive-deps, react-hooks/set-state-in-effect, react-hooks/purity */
import Image from "next/image";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,Camera,CheckCircle2,ChevronRight,Clock3,FileText,History,MapPin,MessageSquare,Phone,Play,RefreshCw,Route,ShieldAlert,Truck,Wrench} from "lucide-react";
import {AppRole,can,supabaseBrowser} from "@/lib/auth";

type Vehicle={id:string;plate_number:string;vehicle_type:string;status:string;driver_name:string|null;driver_id:string|null;fuel_percent:number|null;last_lat:number|null;last_lng:number|null;last_gps_at:string|null;odometer_km:number|null;capacity_kg:number|null;brand?:string|null;model?:string|null;year?:number|null;vendor_name?:string|null;photo_url?:string|null;device_status?:string|null};
type Driver={id:string;full_name:string;phone:string|null;photo_url?:string|null};
type Order={id:string;order_number:string;customer_name:string|null;origin:string;destination:string;status:string;vehicle_id:string|null;driver_id:string|null;cargo_description:string|null;cargo_weight_kg:number|null;scheduled_at:string|null;eta:string|null;cargo_category?:string|null;cargo_quantity?:number|null;cargo_unit?:string|null;cargo_volume_m3?:number|null;declared_value?:number|null;handling_instructions?:string[]|null;pickup_pic?:string|null;recipient_pic?:string|null;document_url?:string|null};
type Issue={id:string;vehicle_id:string|null;title:string;severity:string;status:string;created_at?:string};
type Fund={id:string;vehicle_id:string|null;order_id:string|null;amount:number;category:string;status:string};
type Health={component:string;status:string;last_checked_at:string|null;next_due_at:string|null;value:string|null};
type Cctv={id:string;camera_name:string;camera_position:string;status:string;last_seen_at:string|null;stream_url:string|null};
type Event={id:string;event_type:string;title:string;description:string|null;occurred_at:string};
type Props={vehicle:Vehicle|null;orders:Order[];drivers:Driver[];issues:Issue[];funds:Fund[];role?:AppRole;onOrder:(id:string)=>void;onAction:(message:string)=>void};

const healthLabel:Record<string,string>={service:"Service rutin",engine_oil:"Oli mesin",tires:"Ban & tekanan",brakes:"Rem",battery:"Aki",vehicle_tax:"Pajak kendaraan",stnk:"STNK",kir:"KIR",insurance:"Asuransi",gps_cctv:"GPS / CCTV",safety_kit:"APAR / P3K"};
const statusLabel:Record<string,string>={in_transit:"Mengangkut",pickup:"Menuju pickup",available:"Tersedia",idle:"Idle",maintenance:"Maintenance",incident:"Incident",offline:"GPS Offline"};

export default function FleetControlPanel({vehicle,orders,drivers,issues,funds,role,onOrder,onAction}:Props){
 const sb=supabaseBrowser(),[tab,setTab]=useState<"overview"|"health"|"history"|"cctv">("overview"),[health,setHealth]=useState<Health[]>([]),[cctv,setCctv]=useState<Cctv[]>([]),[events,setEvents]=useState<Event[]>([]),[loading,setLoading]=useState(false);
 const order=useMemo(()=>orders.find(o=>o.vehicle_id===vehicle?.id&&!['delivered','cancelled'].includes(o.status))||orders.find(o=>o.vehicle_id===vehicle?.id),[orders,vehicle]);
 const driver=drivers.find(d=>d.id===(order?.driver_id||vehicle?.driver_id));
 const vehicleIssues=issues.filter(i=>i.vehicle_id===vehicle?.id),vehicleFunds=funds.filter(f=>f.vehicle_id===vehicle?.id||f.order_id===order?.id);
 useEffect(()=>{if(!vehicle||!sb)return;setLoading(true);Promise.all([
  sb.from("vehicle_health_checks").select("component,status,last_checked_at,next_due_at,value").eq("vehicle_id",vehicle.id).order("component"),
  sb.from("cctv_devices").select("id,camera_name,camera_position,status,last_seen_at,stream_url").eq("vehicle_id",vehicle.id),
  sb.from("vehicle_history").select("id,event_type,title,description,occurred_at").eq("vehicle_id",vehicle.id).order("occurred_at",{ascending:false}).limit(20)
 ]).then(([h,c,e])=>{setHealth((h.data||[]) as Health[]);setCctv((c.data||[]) as Cctv[]);setEvents((e.data||[]) as Event[])}).finally(()=>setLoading(false))},[vehicle?.id]);
 if(!vehicle)return <div className="control-empty"><Truck/><b>Pilih armada pada peta atau daftar</b><span>Detail kendaraan, order aktif, muatan, kondisi, dan tindakan akan tampil di sini.</span></div>;
 const operational=can(role,"operate"),lateGps=vehicle.last_gps_at?Date.now()-new Date(vehicle.last_gps_at).getTime()>10*60_000:true;
 const sendQuick=async(message:string)=>{if(!sb||!order)return;await sb.from("trip_communications").insert({vehicle_id:vehicle.id,order_id:order.id,sender_type:"dispatcher",channel:"in_app",message});onAction(`Pesan “${message}” dikirim ke driver`)};
 const reportIncident=async()=>{if(!sb||!operational)return onAction("Role Anda hanya dapat melihat incident");await sb.from("field_issues").insert({vehicle_id:vehicle.id,order_id:order?.id||null,title:"Incident dari Command Center",description:"Laporan awal dibuat melalui tindakan cepat.",severity:"high",status:"reported"});onAction("Laporan incident berhasil dibuat")};
 return <div className="fleet-control">
  <div className="vehicle-hero"><Image src={vehicle.photo_url||"/arah-logo.png"} alt={vehicle.plate_number} fill sizes="360px" unoptimized/><div className="vehicle-hero-shade"/><div className="vehicle-identity"><span>{vehicle.brand||vehicle.vehicle_type} {vehicle.model||""} · {vehicle.year||"-"}</span><h2>{vehicle.plate_number}</h2><b className={`state ${vehicle.status}`}>{statusLabel[vehicle.status]||vehicle.status}</b></div><div className={`device-state ${lateGps?"late":""}`}><i/>{lateGps?"GPS TERLAMBAT":vehicle.device_status||"GPS ONLINE"}</div></div>
  <div className="control-tabs">{([['overview','Operasi'],['health','Health'],['history','History'],['cctv','CCTV']] as const).map(([v,l])=><button key={v} className={tab===v?"active":""} onClick={()=>setTab(v)}>{l}</button>)}</div>
  {loading&&<div className="panel-loading"><RefreshCw/> Memuat data armada…</div>}
  {!loading&&tab==="overview"&&<>
   <div className="driver-card"><div className="driver-photo"><Image src={driver?.photo_url||"/arah-logo.png"} alt={driver?.full_name||"Driver"} fill sizes="48px" unoptimized/></div><div><small>DRIVER AKTIF</small><b>{driver?.full_name||vehicle.driver_name||"Belum ditugaskan"}</b><span>{driver?.phone||"Nomor kontak belum tersedia"}</span></div>{driver?.phone&&<a href={`tel:${driver.phone}`} title="Telepon driver"><Phone/></a>}</div>
   <div className="telemetry-grid"><Metric label="Lokasi terakhir" value={vehicle.last_lat&&vehicle.last_lng?`${vehicle.last_lat.toFixed(4)}, ${vehicle.last_lng.toFixed(4)}`:"Tidak tersedia"}/><Metric label="GPS update" value={vehicle.last_gps_at?new Date(vehicle.last_gps_at).toLocaleTimeString("id-ID"):"Offline"}/><Metric label="BBM" value={`${vehicle.fuel_percent??0}%`}/><Metric label="Odometer" value={`${Number(vehicle.odometer_km||0).toLocaleString("id-ID")} km`}/></div>
   {order?<div className="active-order-card"><div className="order-heading"><div><small>ORDER & MUATAN AKTIF</small><b>{order.order_number}</b></div><button onClick={()=>onOrder(order.id)}>Detail <ChevronRight/></button></div><h3>{order.cargo_description||"Muatan belum diisi"}</h3><div className="cargo-chips"><span>{order.cargo_category||"General Cargo"}</span><span>{order.cargo_quantity||1} {order.cargo_unit||"shipment"}</span><span>{Number(order.cargo_weight_kg||0).toLocaleString("id-ID")} kg</span>{order.cargo_volume_m3&&<span>{order.cargo_volume_m3} m³</span>}</div>{order.handling_instructions?.length?<div className="handling"><ShieldAlert/>{order.handling_instructions.join(" · ")}</div>:null}<div className="route-progress"><div><MapPin/><span><small>ASAL</small><b>{order.origin}</b></span></div><i/><div><Route/><span><small>TUJUAN</small><b>{order.destination}</b></span></div></div><div className="eta-row"><Clock3/><span>Estimasi tiba</span><b>{order.eta?new Date(order.eta).toLocaleString("id-ID",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"short"}):"Belum tersedia"}</b></div></div>:<div className="no-order">Armada ini belum memiliki order aktif.</div>}
   <div className="quick-actions"><button onClick={()=>setTab("cctv")}><Camera/> CCTV</button><button disabled={!order} onClick={()=>sendQuick("Konfirmasi posisi")}><MessageSquare/> Pesan</button><a className={!driver?.phone?"disabled":""} href={driver?.phone?`tel:${driver.phone}`:undefined}><Phone/> Call</a><button onClick={()=>setTab("history")}><Play/> Playback</button><button disabled={!operational} onClick={reportIncident}><AlertTriangle/> Incident</button><button disabled={!operational} onClick={()=>onAction(order?"Mode reassign order dibuka":"Pilih order untuk assignment")}><RefreshCw/> {order?"Reassign":"Assign"}</button></div>
   <div className="quick-message"><span>Pesan cepat:</span>{["Konfirmasi posisi","Berhenti aman","Hubungi dispatcher"].map(x=><button key={x} disabled={!order} onClick={()=>sendQuick(x)}>{x}</button>)}</div>
  </>}
  {!loading&&tab==="health"&&<><div className="health-summary"><Wrench/><div><b>{health.filter(x=>x.status==="ok").length}/{health.length} komponen layak</b><span>Assignment otomatis dibatasi jika komponen kritis tidak layak.</span></div></div><div className="health-list">{health.map(x=><article key={x.component}><span className={`health-icon ${x.status}`}><CheckCircle2/></span><div><b>{healthLabel[x.component]||x.component}</b><small>{x.value||"Pemeriksaan tercatat"}</small></div><time>{x.next_due_at?`Due ${new Date(x.next_due_at).toLocaleDateString("id-ID")}`:"Aktif"}</time><em className={x.status}>{x.status}</em></article>)}</div></>}
  {!loading&&tab==="history"&&<><div className="history-summary"><History/><span><b>Riwayat terpadu armada</b><small>{vehicleIssues.length} incident · {vehicleFunds.length} transaksi perjalanan</small></span></div><div className="timeline-list">{events.map(x=><article key={x.id}><i/><div><small>{new Date(x.occurred_at).toLocaleString("id-ID")}</small><b>{x.title}</b><span>{x.description}</span></div></article>)}</div></>}
  {!loading&&tab==="cctv"&&<><div className="cctv-grid">{cctv.map(x=><article key={x.id}><div className="cctv-screen"><Camera/><span>LIVE PREVIEW</span><b>{x.camera_position}</b><time>{x.last_seen_at?new Date(x.last_seen_at).toLocaleTimeString("id-ID"):"OFFLINE"}</time></div><div><span><i className={x.status}/>{x.camera_name}</span><button onClick={()=>onAction(`Audit akses CCTV ${x.camera_name} tercatat`)}>{x.status==="online"?"Buka Live":"Minta Rekaman"}</button></div></article>)}</div><div className="cctv-note"><FileText/> Setiap akses, snapshot, dan permintaan rekaman disimpan dalam audit trail.</div></>}
 </div>
}

function Metric({label,value}:{label:string;value:string}){return <div><small>{label}</small><b>{value}</b></div>}
