create extension if not exists "pgcrypto";
create type public.vehicle_status as enum ('available','in_transit','maintenance','offline');
create type public.order_status as enum ('planned','assigned','in_transit','delivered','cancelled');
create type public.issue_severity as enum ('low','medium','high','critical');
create type public.approval_status as enum ('pending','approved','rejected');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role text not null default 'viewer' check (role in ('super_admin','fleet_manager','dispatcher','finance_approver','viewer')), operational_scope text not null default 'all', created_at timestamptz not null default now());
create table public.vehicles (id uuid primary key default gen_random_uuid(), plate_number text unique not null, vehicle_type text not null, status public.vehicle_status not null default 'available', driver_name text, fuel_percent int check (fuel_percent between 0 and 100), last_lat double precision, last_lng double precision, last_gps_at timestamptz, created_at timestamptz not null default now());
create table public.orders (id uuid primary key default gen_random_uuid(), order_number text unique not null, vehicle_id uuid references public.vehicles(id), origin text not null, destination text not null, status public.order_status not null default 'planned', scheduled_at timestamptz, eta timestamptz, created_at timestamptz not null default now());
create table public.gps_positions (id bigint generated always as identity primary key, vehicle_id uuid not null references public.vehicles(id) on delete cascade, latitude double precision not null, longitude double precision not null, speed_kph numeric(6,2) default 0, heading numeric(6,2), recorded_at timestamptz not null default now());
create index gps_positions_vehicle_time on public.gps_positions(vehicle_id, recorded_at desc);
create table public.routes (id uuid primary key default gen_random_uuid(), order_id uuid references public.orders(id) on delete cascade, geometry jsonb not null, distance_km numeric(10,2), duration_minutes int, route_provider text default 'demo', created_at timestamptz not null default now());
create table public.operational_funds (id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicles(id), order_id uuid references public.orders(id), category text not null, amount numeric(15,2) not null check(amount > 0), status public.approval_status not null default 'pending', requested_by uuid references public.profiles(id), approved_by uuid references public.profiles(id), created_at timestamptz not null default now());
create table public.field_issues (id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicles(id), order_id uuid references public.orders(id), title text not null, description text, severity public.issue_severity not null default 'medium', resolved_at timestamptz, reported_by uuid references public.profiles(id), created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.vehicles enable row level security; alter table public.orders enable row level security; alter table public.gps_positions enable row level security; alter table public.routes enable row level security; alter table public.operational_funds enable row level security; alter table public.field_issues enable row level security;
create policy "authenticated read profiles" on public.profiles for select to authenticated using (true); create policy "authenticated read vehicles" on public.vehicles for select to authenticated using (true); create policy "authenticated read orders" on public.orders for select to authenticated using (true); create policy "authenticated read gps" on public.gps_positions for select to authenticated using (true); create policy "authenticated read routes" on public.routes for select to authenticated using (true); create policy "authenticated read funds" on public.operational_funds for select to authenticated using (true); create policy "authenticated read issues" on public.field_issues for select to authenticated using (true);
create policy "admins manage profiles" on public.profiles for all to authenticated using ((select role from public.profiles where id = auth.uid()) = 'super_admin') with check ((select role from public.profiles where id = auth.uid()) = 'super_admin');
create policy "operations manage vehicles" on public.vehicles for all to authenticated using ((select role from public.profiles where id = auth.uid()) in ('super_admin','fleet_manager','dispatcher')) with check ((select role from public.profiles where id = auth.uid()) in ('super_admin','fleet_manager','dispatcher'));
create policy "operations manage orders" on public.orders for all to authenticated using ((select role from public.profiles where id = auth.uid()) in ('super_admin','fleet_manager','dispatcher')) with check ((select role from public.profiles where id = auth.uid()) in ('super_admin','fleet_manager','dispatcher'));
create policy "finance manage funds" on public.operational_funds for all to authenticated using ((select role from public.profiles where id = auth.uid()) in ('super_admin','finance_approver')) with check ((select role from public.profiles where id = auth.uid()) in ('super_admin','finance_approver'));
create policy "operations manage issues" on public.field_issues for all to authenticated using ((select role from public.profiles where id = auth.uid()) in ('super_admin','fleet_manager','dispatcher')) with check ((select role from public.profiles where id = auth.uid()) in ('super_admin','fleet_manager','dispatcher'));
alter publication supabase_realtime add table public.gps_positions, public.vehicles, public.orders, public.operational_funds, public.field_issues;
