"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import Image from "next/image";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowLeft,BellRing,Building2,ChevronRight,Clock3,History,Save,Settings2,ShieldCheck,Users} from "lucide-react";
import {AppRole,can,supabaseBrowser} from "@/lib/auth";

type Branch={id:string;code:string|null;name:string;address:string|null;active?:boolean};
type Profile={id:string;full_name:string;role:AppRole;operational_scope:string;branch_id:string|null;status:string};
type Audit={id:number;action:string;entity_type:string;entity_id:string|null;created_at:string;actor_id:string|null};
type Ops={timezone:string;gps_stale_minutes:number;sla_warning_minutes:number;sla_scan_minutes:number;company_name:string};
const roleLabel:Record<AppRole,string>={super_admin:"Super Admin",fleet_manager:"Fleet Manager",dispatcher:"Dispatcher",finance_approver:"Finance Approver",viewer:"Viewer"};
const defaults:Ops={timezone:"Asia/Jakarta",gps_stale_minutes:10,sla_warning_minutes:30,sla_scan_minutes:5,company_name:"ARAH Fleet Command Center"};

export default function SettingsPage(){
 const sb=supabaseBrowser();
 const [role,setRole]=useState<AppRole>(),[uid,setUid]=useState(""),[tab,setTab]=useState("general"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const [ops,setOps]=useState<Ops>(defaults),[branches,setBranches]=useState<Branch[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[audits,setAudits]=useState<Audit[]>([]);
 const [branch,setBranch]=useState({code:"",name:"",address:""});
 async function load(){if(!sb)return;const {data:{user}}=await sb.auth.getUser();if(!user)return;setUid(user.id);const [{data:me},{data:s},{data:b},{data:p},{data:a}]=await Promise.all([sb.from("profiles").select("role").eq("id",user.id).single(),sb.from("app_settings").select("value").eq("key","operations").maybeSingle(),sb.from("branches").select("id,code,name,address,active").order("name"),sb.from("profiles").select("id,full_name,role,operational_scope,branch_id,status").order("full_name"),sb.from("audit_logs").select("id,action,entity_type,entity_id,created_at,actor_id").order("created_at",{ascending:false}).limit(100)]);setRole(me?.role);if(s?.value)setOps({...defaults,...s.value});setBranches(b||[]);setProfiles((p||[]) as Profile[]);setAudits(a||[])}
 useEffect(()=>{load()},[]);
 async function log(action:string,type:string,id?:string,metadata:Record<string,unknown>={}){await sb?.from("audit_logs").insert({actor_id:uid,action,entity_type:type,entity_id:id,metadata})}
 async function saveOps(e:React.FormEvent){e.preventDefault();if(!can(role,"sla"))return;setBusy(true);const {error}=await sb!.from("app_settings").update({value:ops,updated_by:uid,updated_at:new Date().toISOString()}).eq("key","operations");if(!error)await log("settings.operations.updated","app_settings","operations",ops);setBusy(false);setMessage(error?.message||"Pengaturan operasional berhasil disimpan.");load()}
 async function addBranch(e:React.FormEvent){e.preventDefault();if(!can(role,"branches"))return;setBusy(true);const {data,error}=await sb!.from("branches").insert({...branch,active:true}).select("id").single();if(!error){await log("branch.created","branch",data.id,{code:branch.code,name:branch.name});setBranch({code:"",name:"",address:""})}setBusy(false);setMessage(error?.message||"Cabang berhasil ditambahkan.");load()}
 async function toggleBranch(x:Branch){if(!can(role,"branches"))return;const active=x.active===false;const {error}=await sb!.from("branches").update({active}).eq("id",x.id);if(!error)await log(active?"branch.activated":"branch.deactivated","branch",x.id);setMessage(error?.message||`Cabang ${active?"diaktifkan":"dinonaktifkan"}.`);load()}
 async function updateUser(id:string,patch:Partial<Profile>){if(!can(role,"users"))return;const before=profiles.find(x=>x.id===id);const {error}=await sb!.from("profiles").update({...patch,updated_at:new Date().toISOString()}).eq("id",id);if(!error)await log("user.access.updated","profile",id,{before,changes:patch});setMessage(error?.message||"Hak akses pengguna diperbarui.");load()}
 const tabs=[['general','Umum',Settings2],['branches','Cabang',Building2],['users','Pengguna & Akses',Users],['sla','SLA & Notifikasi',BellRing],['audit','Audit Log',History]] as const;
 if(role&&!can(role,"settings"))return <main className="management-page"><section className="access-denied"><ShieldCheck/><h1>Akses dibatasi</h1><p>Role Anda tidak memiliki akses ke pengaturan.</p><Link href="/">Kembali</Link></section></main>;
 return <main className="settings-page"><header className="management-topbar"><Link href="/" className="back-button"><ArrowLeft/></Link><Image src="/arah-logo.svg" width={44} height={44} alt="ARAH"/><div><b>ARAH</b><span>SYSTEM SETTINGS</span></div><div className="settings-role">{role?roleLabel[role]:"Memuat…"}</div></header><div className="settings-layout"><aside><p>ADMINISTRATION</p>{tabs.map(([id,label,Icon])=>{const allowed=id!=="users"||can(role,"users");return allowed&&<button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><Icon/><span>{label}</span><ChevronRight/></button>})}</aside><section className="settings-workspace"><div className="settings-heading"><p>ARAH / SETTINGS</p><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1><span>Konfigurasi tersimpan, tervalidasi, dan tercatat dalam audit log.</span></div>{message&&<div className="management-message">{message}</div>}
 {tab==="general"&&<form className="settings-card settings-form" onSubmit={saveOps}><h2>Identitas & regional</h2><label>Nama sistem<input value={ops.company_name} onChange={e=>setOps({...ops,company_name:e.target.value})}/></label><label>Timezone<select value={ops.timezone} onChange={e=>setOps({...ops,timezone:e.target.value})}><option>Asia/Jakarta</option><option>Asia/Makassar</option><option>Asia/Jayapura</option></select></label><button disabled={busy||!can(role,"sla")}><Save/> Simpan perubahan</button></form>}
 {tab==="branches"&&<div className="settings-grid"><form className="settings-card settings-form" onSubmit={addBranch}><h2>Tambah cabang/depot</h2><label>Kode<input required maxLength={12} value={branch.code} onChange={e=>setBranch({...branch,code:e.target.value.toUpperCase()})}/></label><label>Nama<input required value={branch.name} onChange={e=>setBranch({...branch,name:e.target.value})}/></label><label>Alamat<input value={branch.address} onChange={e=>setBranch({...branch,address:e.target.value})}/></label><button disabled={busy||!can(role,"branches")}><Building2/> Tambah cabang</button></form><div className="settings-card"><h2>Daftar cabang</h2><div className="settings-list">{branches.map(x=><article key={x.id}><div><b>{x.code||"—"} · {x.name}</b><small>{x.address||"Alamat belum diisi"}</small></div><button disabled={!can(role,"branches")} onClick={()=>toggleBranch(x)}>{x.active===false?"Aktifkan":"Nonaktifkan"}</button></article>)}</div></div></div>}
 {tab==="users"&&<div className="settings-card"><div className="card-heading"><div><h2>Role & operational scope</h2><p>Perubahan berlaku pada sesi berikutnya dan direkam otomatis.</p></div><Link href="/users">Undang pengguna</Link></div><div className="table-wrap"><table className="users-table"><thead><tr><th>Pengguna</th><th>Role</th><th>Scope</th><th>Cabang</th><th>Status</th></tr></thead><tbody>{profiles.map(p=><tr key={p.id}><td><b>{p.full_name}</b></td><td><select value={p.role} disabled={p.id===uid} onChange={e=>updateUser(p.id,{role:e.target.value as AppRole})}>{Object.entries(roleLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></td><td><select value={p.operational_scope} onChange={e=>updateUser(p.id,{operational_scope:e.target.value,branch_id:e.target.value==="all"?null:p.branch_id})}><option value="all">Semua</option><option value="branch">Cabang</option></select></td><td><select value={p.branch_id||""} disabled={p.operational_scope==="all"} onChange={e=>updateUser(p.id,{branch_id:e.target.value||null})}><option value="">Pilih</option>{branches.filter(x=>x.active!==false).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></td><td><select value={p.status} disabled={p.id===uid} onChange={e=>updateUser(p.id,{status:e.target.value})}><option value="active">Aktif</option><option value="invited">Diundang</option><option value="suspended">Suspend</option></select></td></tr>)}</tbody></table></div></div>}
 {tab==="sla"&&<form className="settings-card settings-form" onSubmit={saveOps}><h2>Monitoring operasional</h2><label>GPS dianggap stale setelah (menit)<input type="number" min="1" max="1440" value={ops.gps_stale_minutes} onChange={e=>setOps({...ops,gps_stale_minutes:Number(e.target.value)})}/></label><label>Peringatan sebelum SLA (menit)<input type="number" min="5" max="1440" value={ops.sla_warning_minutes} onChange={e=>setOps({...ops,sla_warning_minutes:Number(e.target.value)})}/></label><label>Interval pemeriksaan SLA (menit)<input type="number" min="1" max="60" value={ops.sla_scan_minutes} onChange={e=>setOps({...ops,sla_scan_minutes:Number(e.target.value)})}/></label><div className="settings-note"><Clock3/> Jadwal cron tetap perlu diaktifkan satu kali di Supabase.</div><button disabled={busy||!can(role,"sla")}><Save/> Simpan konfigurasi</button></form>}
 {tab==="audit"&&<div className="settings-card"><h2>Aktivitas pengaturan terbaru</h2>{can(role,"audit")?<div className="settings-list audit-list">{audits.map(a=><article key={a.id}><div><b>{a.action}</b><small>{a.entity_type} · {a.entity_id||"system"}</small></div><time>{new Date(a.created_at).toLocaleString("id-ID")}</time></article>)}</div>:<p>Role Anda tidak dapat melihat audit log.</p>}</div>}
 </section></div></main>;
}
